ProyectosWeb/pro1/django/apps/users/urls.py
from django.contrib import admin
from django.urls import path
from apps.users import views

app_name = 'users_app'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('log-out/', views.Logout.as_view(), name='logout'),
    path('up-pass/', views.Upass.as_view(), name='up-pass'),
    path('users/', views.UsersList.as_view(), name='users'),
]

ProyectosWeb/pro1/django/rcd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('apps.core.urls')),
    path('', include('apps.users.urls')),
    path('', include('apps.sensors.urls')),
    path('', include('apps.chart.urls')),
    path('', include('apps.reports.urls')),
    path('', include('apps.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectosWeb/pro1/django/apps/users/models.py
from django.db import models

# Create your models here.

ProyectosWeb/pro1/django/apps/users/forms.py
from django import forms
from django.contrib.auth import authenticate

class LoginForm(forms.Form):
    username = forms.CharField(
        label='Usuario',
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder' : 'Usuario',
                'id' : 'floatingInput',
                'class' : 'form-control px-5',
            }
        ) 
    )

    password = forms.CharField(
        label='Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder' : 'Contraseña',
                'id' : 'floatingPassword',
                'class' : 'form-control',
            }
        ) 
    )

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']

        if not authenticate(username=username, password=password):
            raise forms.ValidationError('Los datos de usuario no son correctos')

        return self.cleaned_data

        
class UpassForm(forms.Form):
    password1 = forms.CharField(
        label='Contraseña Actual',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder' : 'Contraseña Actual',
                'id' : 'floatingPassword',
                'class' : 'form-control',
            }
        ) 
    )

    password2 = forms.CharField(
        label='Nueva Contraseña',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder' : 'Nueva Contraseña',
                'id' : 'floatingPassword',
                'class' : 'form-control',
            }
        ) 
    )

ProyectosWeb/pro1/django/apps/users/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, FormView, ListView
from django.urls import reverse_lazy, reverse
from .forms import LoginForm, UpassForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.contrib.auth import get_user_model


# Create your views here.
class Login(FormView):
    template_name = 'users/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('sensors_app:sensors')

    def form_valid(self, form):
        user = authenticate(
            username = form.cleaned_data['username'],
            password = form.cleaned_data['password']
        )
        login(self.request, user)        
        return super(Login, self).form_valid(form)


class Logout(View):

    def get(self, request, *args, **kargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'users_app:login'
            )
        )


class Upass(LoginRequiredMixin, FormView):
    template_name = 'users/uppass.html'
    form_class = UpassForm
    success_url = reverse_lazy('users_app:login')
    login_url = reverse_lazy('users_app:login')

    def form_valid(self, form):  
        usuario = self.request.user
        user = authenticate(
            username = usuario.username,
            password = form.cleaned_data['password1']         
        )

        if user:
            new_pass = form.cleaned_data['password2'] 
            usuario.set_password(new_pass)
            usuario.save()

        logout(self.request)
        return super(Upass, self).form_valid(form)


class UsersList(LoginRequiredMixin, ListView):
    template_name = 'users/listusers.html'
    model = get_user_model()
    context_object_name = 'users'
    login_url = reverse_lazy('users_app:login')

    
    
    
  

    

ProyectosWeb/pro1/django/templates/users/listusers.html
{% extends 'include/base.html' %}

{% load static %}

{% block title %}Usuarios{% endblock title %}

{% block style %}

<link rel="stylesheet" href="{% static 'css/sing-change.css' %}">

{% endblock style %}

{% block content %}

<div class="container my-4">

<h2 class="py-4">Bienvenido {{ user.first_name}}</h2>

<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-lg-2 py-1">
            <div class="row">
                <div class="col col-lg-10">Username</div>
                <hr class="border border-danger border-2 opacity-70 na">
                <div class="col">{{ user.username }}</div>
            </div>
        </div>     
        <div class="col-sm-12 col-lg-3 py-1">
            <div class="row">
                <div class="col col-lg-10">Email</div>
                <hr class="border border-danger border-2 opacity-70 na">
                <div class="col">{{ user.email }}</div>
            </div>
        </div>   
        <div class="col-sm-12 col-lg-2 py-1">
            <div class="row">
                <div class="col col-lg-10">Nombre</div>
                <hr class="border border-danger border-2 opacity-70 na">
                <div class="col">{{ user.first_name }}</div>
            </div>
        </div>     
        <div class="col-sm-12 col-lg-2 py-1">
            <div class="row">
                <div class="col col-lg-10">Apellido</div>
                <hr class="border border-danger border-2 opacity-70 na">
                <div class="col">{{ user.last_name }}</div>
            </div>
        </div>  
        <div class="col-sm-12 col-lg-1 py-1">
            <div class="row">
                <div class="col col-lg-10">Estaff</div>
                <hr class="border border-danger border-2 opacity-70 na">
                <div class="col"><input type="checkbox" checked="{{ user.is_staff }}"></div>
            </div>
        </div>     
        <div class="col-sm-12 col-lg-2 py-1">
            <div class="row">                
                <a href="{% url 'users_app:up-pass' %}" class="btn btn-outline-danger sm-auto but">Cambio Pass</a>
            </div>
        </div>             
    </div>  
</div>

</div>


{% endblock content %}

{% block script %}   

{% endblock script %}

ProyectosWeb/pro1/django/templates/users/login.html
{% extends 'include/base.html' %}

{% load static %}

{% block title %}Login{% endblock title %}

{% block style %}

<link href="{% static 'css/sign-in.css' %}" rel="stylesheet">

{% endblock style %}

{% block content %}

<div class="container py-5">
    <form method="post">{% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Bienvenido a Telemetric</h1>
   
       <div class="form-floating py-2">
         {{form.username}}
         <label for="floatingInput">Usuario</label>
       </div>
       <div class="form-floating py-2">
         {{form.password}}
         <label for="floatingPassword">Password</label>
       </div>
       
       <button class="w-100 btn btn-lg btn-primary" type="submit">Ingresar</button>
       <p class="mt-5 mb-3 text-muted">&copy; cpce 2023</p>
   </form>
</div>


{% endblock content %}

{% block script %}   

{% endblock script %}
    

ProyectosWeb/pro1/django/templates/users/uppass.html
{% extends 'include/base.html' %}

{% load static %}

{% block title %}Update Pass{% endblock title %}

{% block style %}

<link href="{% static 'css/sign-in.css' %}" rel="stylesheet">

{% endblock style %}

{% block content %}

<div class="container py-5">
    <form method="post">{% csrf_token %}
        <h1 class="h3 mb-3 fw-normal">Cambio de clave de {{ user.first_name }}</h1>
   
       <div class="form-floating py-2">
         {{form.password1}}
         <label for="floatingInput">Contraseña actual</label>
       </div>
       <div class="form-floating py-2">
         {{form.password2}}
         <label for="floatingPassword">Nueva contraseña</label>
       </div>
       
       <button class="w-100 btn btn-lg btn-primary" type="submit">Ingresar</button>
       <p class="mt-5 mb-3 text-muted">&copy; cpce 2023</p>
   </form>
</div>


{% endblock content %}

{% block script %}   

{% endblock script %}
    