ProyectosWeb/pro1/django/apps/sensors/urls.py
from django.contrib import admin
from django.urls import path
from apps.sensors import views

app_name = 'sensors_app'

urlpatterns = [
    path('sensors/', views.ListSensor.as_view(), name='sensors'),
    path('sensors/<sen>/', views.ListMeasure.as_view(), name='sensors-n'),
]

ProyectosWeb/pro1/django/rcd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('apps.core.urls')),
    path('', include('apps.users.urls')),
    path('', include('apps.sensors.urls')),
    path('', include('apps.chart.urls')),
    path('', include('apps.reports.urls')),
    path('', include('apps.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectosWeb/pro1/django/apps/sensors/models.py
from django.db import models
from apps.api.manager import ApiManager

# Create your models here.
class Equipo(models.Model):
    marca = models.CharField('Marca', max_length=15)
    model = models.CharField('Modelo', max_length=20)
    image = models.ImageField('Imagen', upload_to='sensors')

    def __str__(self):
        return f'{self.marca}'

    
    class Meta:
        verbose_name = 'Equipo'
        verbose_name_plural = 'Equipos'
        

class Sensor(models.Model):
    name = models.CharField('Nombre', max_length=10, default='Sensor N', unique=True)
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE, verbose_name='Equipo', related_name='equipo')
    locate = models.CharField('Instalado en', max_length=20)

    def __str__(self):
        return f'{self.name}'

    
    class Meta:
        verbose_name = 'Sensor'
        verbose_name_plural = 'Sensores'
    

class Variable(models.Model):    
    sensor = models.ForeignKey(Sensor, on_delete=models.CASCADE, verbose_name='sensor', related_name='sensor')
    v1 = models.FloatField('Voltaje L1 - N')
    v2 = models.FloatField('Voltaje L2 - N')
    v3 = models.FloatField('Voltaje L3 - N')

    v13 = models.FloatField('Voltaje L1 - L3')
    v23 = models.FloatField('Voltaje L2 - L3')
    v12 = models.FloatField('Voltaje L1 - L2')

    i1 = models.FloatField('Corriente L1')
    i2 = models.FloatField('Corriente L2')
    i3 = models.FloatField('Corriente L3')

    p1 = models.FloatField('Potencia L1')
    p2 = models.FloatField('Potencia L2')
    p3 = models.FloatField('Potencia L3')

    pa = models.FloatField('Potencia Activa')
    fp = models.FloatField('Factor de potencia')
    hz = models.FloatField('Frecuencia')

    created = models.DateTimeField('Ingresado', auto_now_add=True)


    def __str__(self):
        return f'{self.sensor}'

    
    class Meta:
        verbose_name = 'Medida'
        verbose_name_plural = 'Medidas'


    objects = ApiManager()

ProyectosWeb/pro1/django/apps/sensors/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView
from .models import Sensor, Variable, Equipo
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, Http404, HttpResponseNotFound
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.shortcuts import get_object_or_404


# Create your views here.
class ListSensor(LoginRequiredMixin, ListView):
    template_name = 'sensors/listsensor.html'
    model = Sensor
    context_object_name = 'sensors'
    login_url = reverse_lazy('users_app:login')


class ListMeasure(LoginRequiredMixin, ListView):
    template_name = 'sensors/listmeasure.html'
    model = Variable
    context_object_name = 'me'
    login_url = reverse_lazy('users_app:login') 

    def get_queryset(self):
        queryset = super(ListMeasure, self).get_queryset()
        sensor_b = self.kwargs['sen']    
        try:    
            lista = Variable.objects.filter(sensor_id = sensor_b).latest('created') 
        except Variable.DoesNotExist:
            lista = None
            
        return lista
        
            
        
        
        
        
   



   
    

    

ProyectosWeb/pro1/django/templates/sensors/listmeasure.html
{% extends 'include/base.html' %}

{% load static %}

{% block title %}Sensores{% endblock title %}

{% block style %}

<link rel="stylesheet" href="{% static 'css/list-measure.css' %}">

{% endblock style %}

{% block content %} 


{% if object_list == None %}

<h1 class="my-4">Advetencia</h1>

<p>Aun no existen registros de este sensor.   
  Puese ser que no ha sido habilitado u/o que 
  aún no recibe información desde el remoto</p>

<p>Porfavor, pongase en contacto con su administrador.</p>

<p>Telemetric SPA</p>
  

{% else %}  

<div class="m-4">
    <h1>Mediciones {{ object_list }}</h1>
</div>

  
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-3">   
    <div class="col">
        <div class="card h-100 shadow p-3 mb-1 bg-body-whiterounded">
        <div class="card-body">
            <h5 class="card-title display-6 w-auto text-auto">Voltaje L1 - N</h5>
            <h5 id="v1" class="card-title display-4 text-auto">{{ me.v1 }} V</h5>           
        </div>
      </div>
    </div>

    <div class="col">
        <div class="card h-100 shadow p-3 mb-1 bg-body-whiterounded">
        <div class="card-body">
            <h5 class="card-title display-6 text-auto">Voltaje L2 - N</h5>
            <h5 id="v2" class="card-title display-4 text-auto">{{ me.v2 }} V</h5>    
        </div>
      </div>
    </div>

    <div class="col">
        <div class="card h-100 shadow p-3 mb-1 bg-body-whiterounded">
        <div class="card-body">
            <h5 class="card-title display-6 text-auto">Voltaje L3 - N</h5>
            <h5 id="v3" class="card-title display-4 text-auto">{{ me.v3 }} V</h5>           
        </div>
      </div>
    </div>

    <div class="col">
        <div class="card h-100 shadow p-3 mb-1 bg-body-whiterounded">
        <div class="card-body">
            <h5 class="card-title display-6 text-auto">Voltaje L1 - L3</h5>
            <h5 id="v13" class="card-title display-4 text-auto">{{ me.v13 }} V</h5>           
        </div>
      </div>
    </div>

    <div class="col">
        <div class="card h-100 shadow p-3 mb-1 bg-body-whiterounded">
        <div class="card-body">
            <h5 class="card-title display-6 text-auto">Voltaje L2 - L3</h5>
            <h5 id="v23" class="card-title display-4 text-auto">{{ me.v23 }} V</h5>           
        </div>
      </div>
    </div>

    <div class="col">
        <div class="card h-100 shadow p-3 mb-1 bg-body-whiterounded">
        <div class="card-body">
            <h5 class="card-title display-6 text-auto">Voltaje L1 - L2</h5>
            <h5 id="v12" class="card-title display-4 text-auto">{{ me.v23 }} V</h5>           
        </div>
      </div>
    </div>

    <div class="col">
        <div class="card h-100 shadow p-3 mb-1 bg-body-whiterounded">
        <div class="card-body">
            <h5 class="card-title display-6 text-auto">Corriente L1</h5>
            <h5 id="i1" class="card-title display-4 text-auto">{{ me.i1 }} A</h5>           
        </div>
      </div>
    </div>

    <div class="col">
        <div class="card h-100 shadow p-3 mb-1 bg-body-whiterounded">
        <div class="card-body">
            <h5 class="card-title display-6 text-auto">Corriente L2</h5>
            <h5 id="i2" class="card-title display-4 text-auto">{{ me.i2 }} A</h5>           
        </div>
      </div>
    </div>

    <div class="col">
        <div class="card h-100 shadow p-3 mb-1 bg-body-whiterounded">
        <div class="card-body">
            <h5 class="card-title display-6 text-auto">Corriente L3</h5>
            <h5 id="i3" class="card-title display-4 text-auto">{{ me.i3 }} A</h5>           
        </div>
      </div>
    </div>

    <div class="col">
        <div class="card h-100 shadow p-3 mb-1 bg-body-whiterounded">
        <div class="card-body">
            <h5 class="card-title display-6 text-auto">Potencia L1</h5>
            <h5 id="p1" class="card-title display-4 text-auto">{{ me.p1 }} KW</h5>           
        </div>
      </div>
    </div>

    <div class="col">
        <div class="card h-100 shadow p-3 mb-1 bg-body-whiterounded">
        <div class="card-body">
            <h5 class="card-title display-6 text-auto">Potencia L2</h5>
            <h5 id="p2" class="card-title display-4 text-auto">{{ me.p2 }} KW</h5>           
        </div>
      </div>
    </div>

    <div class="col">
        <div class="card h-100 shadow p-3 mb-1 bg-body-whiterounded">
        <div class="card-body">
            <h5 class="card-title display-6 text-auto">Potencia L3</h5>
            <h5 id="p3" class="card-title display-4 text-auto">{{ me.p3 }} KW</h5>           
        </div>
      </div>
    </div>

    <div class="col">
        <div class="card h-100 shadow p-3 mb-1 bg-body-whiterounded">
        <div class="card-body">
            <h5 class="card-title display-6 text-auto">Potencia Activa</h5>
            <h5 id="pa" class="card-title display-4 text-auto">{{ me.pa }} KW/h</h5>           
        </div>
      </div>
    </div>

    <div class="col">
        <div class="card h-100 shadow p-3 mb-1 bg-body-whiterounded">
        <div class="card-body">
            <h5 class="card-title display-6 text-auto">Factor Potencia</h5>
            <h5 id="fp" class="card-title display-4 text-auto">{{ me.fp }}</h5>           
        </div>
      </div>
    </div>

    <div class="col">
        <div class="card h-100 shadow p-3 mb-1 bg-body-whiterounded">
        <div class="card-body">
            <h5 class="card-title display-6 text-auto">Frecuencia</h5>
            <h5 id="hz" class="card-title display-4 text-auto">{{ me.hz }} Hz</h5>           
        </div>
      </div>
    </div>   

</div>

<script>
  var socket = new WebSocket('ws://localhost:8000/ws/<sen>/');
  const API = "http://127.0.0.1:8000/api-last/{{ me.sensor.id }}"

  socket.onmessage = function(e){          
    getData();  
  }

  const getData = async () => {
    const res = await fetch(API);
    const data = await res.json();

    console.log(data);
    
    let v1 = data[0].me.vln.v1 + " V";
    let v2 = data[0].me.vln.v2 + " V";
    let v3 = data[0].me.vln.v3 + " V";

    let v13 = data[0].me.vll.v13 + " V";
    let v23 = data[0].me.vll.v23 + " V";
    let v12 = data[0].me.vll.v12 + " V";

    let i1 = data[0].me.il.i1 + " A";
    let i2 = data[0].me.il.i2 + " A";
    let i3 = data[0].me.il.i3 + " A";

    let p1 = data[0].me.pl.p1 + " Kw";
    let p2 = data[0].me.pl.p2 + " Kw";
    let p3 = data[0].me.pl.p3 + " Kw";

    let pa = data[0].me.ot.pa + " Kw/h";
    let fp = data[0].me.ot.fp;
    let hz = data[0].me.ot.hz + " Hz"; 

    document.getElementById("v1").innerHTML = float(v1); 
    document.getElementById("v2").innerHTML = float(v2); 
    document.getElementById("v3").innerHTML = float(v3); 

    document.getElementById("v13").innerHTML = float(v13); 
    document.getElementById("v23").innerHTML = float(v23); 
    document.getElementById("v12").innerHTML = float(v12); 

    document.getElementById("i1").innerHTML = float(i1); 
    document.getElementById("i2").innerHTML = float(i2); 
    document.getElementById("i3").innerHTML = float(i3); 

    document.getElementById("p1").innerHTML = float(p1); 
    document.getElementById("p2").innerHTML = float(p2); 
    document.getElementById("p3").innerHTML = float(p3); 

    document.getElementById("pa").innerHTML = float(pa); 
    document.getElementById("fp").innerHTML = float(fp); 
    document.getElementById("hz").innerHTML = float(hz); 
   
  }

  
</script>

{% endif %}


{% endblock content %}

{% block script %}   

{% endblock script %}

ProyectosWeb/pro1/django/templates/sensors/listsensor.html
{% extends 'include/base.html' %}

{% load static %}

{% block title %}Sensores{% endblock title %}

{% block style %}

<link rel="stylesheet" href="{% static 'css/list-sensors.css' %}">

{% endblock style %}

{% block content %}  

<div class="m-4">
    <h1>Sensores instalados</h1>
</div>

<div class="row row-cols-1 row-cols-md-3 row-cols-lg-4 g-3">
    {% for s in sensors %} 
    <div class="col">
        <a href="{% url 'sensors_app:sensors-n' s.id %}" style="text-decoration: none;">
      <div class="card h-100 shadow p-3 mb-5 bg-body-whiterounded">
        <img src="{{ s.equipo.image.url }}" class="card-img-top">
        <div class="card-body">
          <h5 class="card-title">{{ s.name }}</h5>
          <p class="card-text">{{ s.equipo }} {{ s.equipo.model }}</p>
          <p class="card-text"><small class="text-muted">{{ s.locate }}</small></p>
        </div>
      </div>
    </a>
    </div>    

    {% endfor %}  
  
  </div>

{% endblock content %}

{% block script %}   

{% endblock script %}