ProyectosWeb/pro1/django/apps/chart/urls.py
from django.contrib import admin
from django.urls import path
from apps.chart import views

app_name = 'chart_app'

urlpatterns = [
    path('chart/', views.Chart.as_view(), name='chart'),  
]

ProyectosWeb/pro1/django/apps/reports/urls.py
from django.contrib import admin
from django.urls import path
from apps.reports import views

app_name = 'report_app'

urlpatterns = [
    path('report/', views.Report.as_view(), name='report'),  
]

ProyectosWeb/pro1/django/apps/sensors/urls.py
from django.contrib import admin
from django.urls import path
from apps.sensors import views

app_name = 'sensors_app'

urlpatterns = [
    path('sensors/', views.ListSensor.as_view(), name='sensors'),
    path('sensors/<sen>/', views.ListMeasure.as_view(), name='sensors-n'),
]

ProyectosWeb/pro1/django/apps/users/urls.py
from django.contrib import admin
from django.urls import path
from apps.users import views

app_name = 'users_app'

urlpatterns = [
    path('', views.Login.as_view(), name='login'),
    path('log-out/', views.Logout.as_view(), name='logout'),
    path('up-pass/', views.Upass.as_view(), name='up-pass'),
    path('users/', views.UsersList.as_view(), name='users'),
]

ProyectosWeb/pro1/django/rcd/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('', include('apps.core.urls')),
    path('', include('apps.users.urls')),
    path('', include('apps.sensors.urls')),
    path('', include('apps.chart.urls')),
    path('', include('apps.reports.urls')),
    path('', include('apps.api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectosWeb/pro1/django/templates/include/aside.html
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse>
    <div class="position-sticky pt-3 sidebar-sticky">
      <ul class="nav flex-column nav-justified">       
       
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/sensors/' %} active {% endif %}" href="{% url 'sensors_app:sensors' %}">
            <span data-feather="thermometer" class="align-text-bottom"></span>
            Sensores
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/chart/' %} active {% endif %}" href="{% url 'chart_app:chart' %}">
            <span data-feather="pie-chart" class="align-text-bottom"></span>
            Graficos
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/report/' %} active {% endif %}" href="{% url 'report_app:report' %}">
            <span data-feather="send" class="align-text-bottom"></span>
            Reportes
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == '/users/' %} active {% endif %}" href="{% url 'users_app:users' %}">
            <span data-feather="user" class="align-text-bottom"></span>
            Usuario
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users_app:logout' %}">
            <span data-feather="log-out" class="align-text-bottom"></span>
            Logout
          </a>
        </li>
      </ul>
    </div>
  </nav>

ProyectosWeb/pro1/django/templates/include/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
    </style>

    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">  
    {% block style %}{% endblock style %}
    {% block scripth %}{% endblock scripth %} 
    
</head>

<body>  

  {% include 'include/head.html' %}
  
 
  <div class="container-fluid">
    <div class="row">

      {% include 'include/aside.html' %}      
  
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
          {% block content %}
    
    
          {% endblock content %}          
      </main>
    </div>
  </div> 

    {% block script %}{% endblock script %} 

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous">
    </script><script src="{% static 'js/dashboard.js' %}"></script>
  </body>
</html>

ProyectosWeb/pro1/django/templates/include/head.html
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3 fs-6" href="#">Telemetric</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>   
</header>